name: CodeCheck

on:
  push:
    branches:
      - 'main/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dokcer-compose up
      run: |
        docker-compose build
        docker-compose up -d
    - name: composer install
      run: |
        docker-compose exec -T php bash -c "composer install"
    - name: phpunit
      run: |
        docker-compose exec -T php bash -c "php vendor/bin/phpunit"
    - name: php-cs-fixer
      run: |
        docker-compose exec -T php bash -c "vendor/bin/php-cs-fixer fix --dry-run"
